package com.example.reservarestaurantes

import android.database.Cursor
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.MenuItem
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.cursoradapter.widget.SimpleCursorAdapter
import androidx.loader.app.LoaderManager
import androidx.loader.content.CursorLoader
import androidx.loader.content.Loader
import androidx.navigation.fragment.findNavController
import com.example.reservarestaurantes.databinding.FragmentInserirClientesBinding
import com.example.reservarestaurantes.databinding.FragmentInserirReservaBinding
import com.google.android.material.snackbar.Snackbar


/**
 * A simple [Fragment] subclass.
 * Use the [InserirClientesFragment.newInstance] factory method to
 * create an instance of this fragment.
 */
class InserirClientesFragment : Fragment(),LoaderManager.LoaderCallbacks<Cursor> {
    private var _binding: FragmentInserirClientesBinding? = null

    private val binding get() =_binding!!


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = FragmentInserirClientesBinding.inflate(inflater, container, false)


        return binding.root
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }


    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val activity = requireActivity() as MainActivity
        activity.fragment = this
        activity.idMenuAtual =R.menu.menu_edicao
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param id The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    override fun onCreateLoader(id: Int, args: Bundle?): Loader<Cursor> =
        CursorLoader(
            requireContext(),
            ContentProviderReservas.ENDERECO_CLIENTES,
            TabelaBDClientes.TODOS_CAMPOS_CIENTES,
            null,
            null,
            "${TabelaBDClientes.CAMPO_NOME}"
        )

    /**
     * Called when a previously created loader has finished its load.  Note
     * that normally an application is *not* allowed to commit fragment
     * transactions while in this call, since it can happen after an
     * activity's state is saved.  See [ FragmentManager.openTransaction()][androidx.fragment.app.FragmentManager.beginTransaction] for further discussion on this.
     *
     *
     * This function is guaranteed to be called prior to the release of
     * the last data that was supplied for this Loader.  At this point
     * you should remove all use of the old data (since it will be released
     * soon), but should not do your own release of the data since its Loader
     * owns it and will take care of that.  The Loader will take care of
     * management of its data so you don't have to.  In particular:
     *
     *
     *  *
     *
     *The Loader will monitor for changes to the data, and report
     * them to you through new calls here.  You should not monitor the
     * data yourself.  For example, if the data is a [android.database.Cursor]
     * and you place it in a [android.widget.CursorAdapter], use
     * the [android.widget.CursorAdapter.CursorAdapter] constructor *without* passing
     * in either [android.widget.CursorAdapter.FLAG_AUTO_REQUERY]
     * or [android.widget.CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER]
     * (that is, use 0 for the flags argument).  This prevents the CursorAdapter
     * from doing its own observing of the Cursor, which is not needed since
     * when a change happens you will get a new Cursor throw another call
     * here.
     *  *  The Loader will release the data once it knows the application
     * is no longer using it.  For example, if the data is
     * a [android.database.Cursor] from a [android.content.CursorLoader],
     * you should not call close() on it yourself.  If the Cursor is being placed in a
     * [android.widget.CursorAdapter], you should use the
     * [android.widget.CursorAdapter.swapCursor]
     * method so that the old Cursor is not closed.
     *
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that has finished.
     * @param data The data generated by the Loader.
     */
    override fun onLoadFinished(loader: Loader<Cursor>, data: Cursor?) {
        val adapterClientes = SimpleCursorAdapter(
            requireContext(),
            android.R.layout.simple_list_item_1,
            data,
            arrayOf(TabelaBDClientes.CAMPO_NOME),
            intArrayOf(android.R.id.text1),
            0
        )

        //binding.inputTextClienteNome.adapter = adapterClientes
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that is being reset.
     */
    override fun onLoaderReset(loader: Loader<Cursor>) {
        if(_binding == null)return
        //binding.inputTextClienteNome.adapter = null
    }

    fun processaOpcaoMenu(item: MenuItem) : Boolean =
        when(item.itemId) {
            R.id.action_guardar -> {
                guardar()
                true
            }
            R.id.action_cancelar -> {
                voltarListaClientes()
                true
            }
            else -> false
        }

    fun guardar(){
        val nomeCliente = binding.inputTextClienteNome.text.toString()
        if (nomeCliente.isBlank()){
           binding.inputTextClienteNome.error = getString(R.string.clienteReservaObrigatorio)
           binding.inputTextClienteNome.requestFocus()
           return
        }

        val telefoneCliente = binding.inputTextClienteTelefone.text.toString()
        if (telefoneCliente.isBlank()){
            binding.inputTextClienteTelefone.error = getString(R.string.clienteReservaObrigatorio)
            binding.inputTextClienteTelefone.requestFocus()
            return
        }

        val nifCliente = binding.inputTextClienteNif.text.toString()
        if (nifCliente.isBlank()){
            binding.inputTextClienteNif.error = getString(R.string.clienteReservaObrigatorio)
            binding.inputTextClienteNif.requestFocus()
            return
        }

        val moradaCliente = binding.inputTextClienteMorada.text.toString()
        if (moradaCliente.isBlank()){
            binding.inputTextClienteMorada.error = getString(R.string.clienteReservaObrigatorio)
            binding.inputTextClienteMorada.requestFocus()
            return
        }

        insereCliente(nomeCliente, telefoneCliente, nifCliente, moradaCliente)
    }

    private fun insereCliente(nomeCliente: String, telefoneCliente: String, nifCliente: String, moradaCliente: String){
        val clientes = Clientes(nomeCliente, telefoneCliente, nifCliente, moradaCliente)

        val enderecoClienteInserido = requireActivity().contentResolver.insert(ContentProviderReservas.ENDERECO_CLIENTES, clientes.toContentValues())

        if (enderecoClienteInserido == null){
            Snackbar.make(binding.inputTextClienteNome, R.string.erroGuardarCliente, Toast.LENGTH_LONG).show()
            return
        }

        Toast.makeText(requireContext(),R.string.clienteGuardadoSucesso, Toast.LENGTH_LONG).show()
        voltarListaClientes()
    }

    private fun voltarListaClientes(){
        findNavController().navigate(R.id.action_inserirClientesFragment_to_listaClientesFragment)
    }
}